### ISSUE TITLE
Why don't I get any colored text on windows

### ISSUE THREAD

**Issue by rookiebulls** [MasterOdin/crayons#4]
I have to use colorama to "init" before using crayons to output some colored text on windows, otherwise the console just output some ANSI code, without any color.

**Comment by caizixian** [comment]
Could you please paste your code and elaborate on the environment you use (which terminal, etc)

**Comment by rookiebulls** [comment]
@caizixian I am using cmd.exe on Windows 7, just some test code in the python shell.
Please see the image below.
![Image of craynon error](http://olgvodd4s.bkt.clouddn.com/P70213-081923.jpg)

**Comment by rookiebulls** [comment]
@caizixian I am using cmd.exe on Windows 7, just some test code in the python shell.
Please see the image below.
![error image](http://olgvodd4s.bkt.clouddn.com/P70213-081923.jpg)

**Comment by caizixian** [comment]
cmd.exe of Windows 7 doesn't support ANSI escape sequences.

This topic on superuser might helps http://superuser.com/questions/413073/windows-console-with-ansi-colors-handling/

**Comment by MasterOdin** [comment]
This was fixed with #12.
